### PR TITLE
Remove support for numerical input.

### PR DESCRIPTION
**Pull request by mtyaka**
This PR removes support for numeric input feature. Nobody is using that feature anymore and it adds a lot of complexity to the codebase.

**JIRA tickets**: https://openedx.atlassian.net/browse/SOL-1870

**Dependencies**: None

**Sandbox LMS URL**: http://dndv2.opencraft.hosting/
**Sandbox Studio URL**: http://studio-dndv2.opencraft.hosting/

**Testing instructions**:

This PR does not add any new features and makes no user-visible changes (assuming users were not using the numeric input feature) so there is no specific functionality to test.
Testers should verify that DnDv2 continues to function correctly.

**Reviewers**
- [x] @e-kolpakov 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=74&repo=edx-solutions%2Fxblock-drag-and-drop-v2

**Comment by e-kolpakov** [comment]
@mtyaka code changes looks good, but documentation (README) still references numerical input.

Also, not sure if it is a regression or worked like that previously, but when you drag an item to a zone, spinner is shown on separate line, doubling item height - I remember at some point it was shown on the same line with item text.

**Comment by bradenmacdonald** [comment]
@e-kolpakov All our demo courses are at https://github.com/open-craft/demo-courses . @mtyaka when you are updating the readme, can you please add a link to the demo course? ( The URL https://github.com/open-craft/demo-courses/archive/drag-and-drop-v2.tar.gz will always download the latest version )

**Comment by mtyaka** [comment]
@e-kolpakov Thanks for the review. I already removed references to numeric input from the [README](https://github.com/open-craft/xblock-drag-and-drop-v2/blob/708fa2954074ed327a20f3837f952fae1707b9a1/README.md). Did I miss some?

Thanks for pointing out the spinner issue, I'm looking into it.

I did not update the demo course yet, I will do that now and add a link to the README.

**Comment by mtyaka** [comment]
@e-kolpakov The spinner is also shown on a separate line using the master branch. I am not sure whether it's a bug or it's supposed to work like that, but it doesn't look like it was introduced by the changes in this PR.
I updated the demo course at http://dndv2.opencraft.hosting to remove the section demoing the numeric input, I updated the export at https://github.com/open-craft/demo-courses/archive/drag-and-drop-v2.tar.gz, and I added a link to the export to the README file.

**Comment by e-kolpakov** [comment]
@mtyaka sorry about README - not sure how I managed to still see numerical-input related sections in it - probably I was thinking I was looking at README on branch, but actually was on master.

:+1:

**Comment by mtyaka** [comment]
@e-kolpakov Did you merge this by accident? We still need a review from TNL.

**Comment by e-kolpakov** [comment]
@mtyaka uhm, yes, sorry,  I've accidentally merge #75 and it was based on this branch.

**Comment by mtyaka** [comment]
@e-kolpakov No worries, I recreated the PR in #78. Can I get you +1 on the new PR, please?

**Pull request merged**
