### PR TITLE
version bump to 7c95f90 commit (updated translations)

### PR DESCRIPTION
**Pull request by umarmughal824**
version bump to 7c95f90 commit (updated translations)

### CODE REVIEW

**Comment by umarmughal824** [comment]
@xitij2000 please review it.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @umarmughal824! I've created [OSPR-2808](https://openedx.atlassian.net/browse/OSPR-2808) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by xitij2000** [comment]
@umarmughal824 I can merge this, but to be clear I can't create a release based on this. That will require merging to master and going through edX review.

**Comment by umarmughal824** [comment]
@xitij2000 but we are using mckinsey-master branch. So obviously in that case, it should be merged in mckinsey-master. Isn't it so?

**Comment by xitij2000** [comment]
@umarmughal824 Tags are not restricted to a single branch, they are global. So tagging a release from mckinsey-master would make that the official release. To get an official tagged release this needs to be merged to the master branch. 

So as I said, I can merge the version bump in the code, but I cannot create a tagged release yet. Also please update the travis config to get the tests to pass.

**Comment by umarmughal824** [comment]
@xitij2000 ok, I will create the PR to master rather than mckinsey-master that will pass the test as well.

**Pull request closed without merging**
