### PR TITLE
Mckin 7635 target zone UI

### PR DESCRIPTION
**Pull request by murad-hubib**
- Highlighted zones with the border
- Dragging an item will make the rest of items dim 

Related Story: https://edx-wiki.atlassian.net/browse/MCKIN-7635

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @murad-hubib! I've created [OSPR-2468](https://openedx.atlassian.net/browse/OSPR-2468) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by bradenmacdonald** [comment]
@mduboseedx Note that this still will need a second review from edX, probably @sanfordstudent.

Also @mduboseedx @sanfordstudent we should move this into the `edx` org soon; I think it's confusing that it's in `edx-solutions`, which is only for historical reasons.

**Comment by murad-hubib** [comment]
@bradenmacdonald  Thanks. Can you please also merge this PR as I don't have rights to merge.

**Comment by sanfordstudent** [comment]
@bradenmacdonald copying a hipchat message I sent you since I'm not sure if you're on our hipchat:

"hey Braden- just wanted to let you know that I think it makes sense to transition drag n drop review duties to someone else at edx and to figure out which team should own it (as opposed to me individually). i'm going to be leaving edx in early August so I won't be around for reviews much longer."

**Comment by mduboseedx** [comment]
@nedbat Were you interested in working more with XBlocks?

**Comment by bradenmacdonald** [comment]
@sanfordstudent Thanks, I don't log into HipChat anymore. Sorry to hear you're leaving, as we'll miss you! Just let us know who ends up taking this one. It's fine if it's a team, though it'd be best if someone from that team can specifically learn about this XBlock in detail and coordinate future reviews. Moving it to the `edx` org on GitHub might be a nice first step for onboarding someone :)

**Comment by viadanna** [comment]
Hello @murad-hubib 

I don't see the behavior described, is this correct?
drag-and-drop

**Comment by murad-hubib** [comment]
Hi @viadanna Thanks, You are right. This ticket is a partial functionality of [7668](https://edx-wiki.atlassian.net/browse/MCKIN-7668) i-e to apply CSS on drop zones when user is dragging an item. This PR is now safe to be merged.

**Comment by viadanna** [comment]
Oh, I was still working with the full acceptance criteria, @murad-hubib 
This is good for merging, @bradenmacdonald @xitij2000

**Pull request merged**
