### PR TITLE
Mention where to locate the block instead of how to install it

### PR DESCRIPTION
**Pull request by clemente**
Explicitly mention where to find this block, because it doesn't appear in the usual place (Advanced) as other xblocks. Remove installation instruction because it doesn't need installation.
Note that the [documentation](http://edx.readthedocs.io/projects/xblock-tutorial/en/latest/edx_platform/devstack.html#add-an-instance-of-the-xblock-to-a-unit) is asking users to look only under „Advanced“.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @clemente! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx-solutions%2Fxblock-drag-and-drop-v2&number=146"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by bradenmacdonald** [comment]
@clemente Is it even still necessary to add "drag_and_drop_v2" to the advanced settings in Studio first?

**Comment by clemente** [comment]
@bradenmacdonald Probably not, because it's already installed as a requirement. Maybe the documentation must cover two cases: older versions, recent versions.

**Comment by bradenmacdonald** [comment]
@clemente No, the documentation does not need to cover older versions. I think you can remove steps 1-3 if you confirm they're not necessary.

**Comment by clemente** [comment]
@bradenmacdonald Confirmed in a recent sandbox that it comes enabled by default, and simplified instructions.

**Pull request merged**
