### PR TITLE
[MCKIN-5776] Support for dynamic generation of target zones and image.

### PR DESCRIPTION
**Pull request by mtyaka**
Instead of providing a custom image, the author can now specify the number of columns and rows and a single zone size and zones arranged in a grid of chosen size will be automatically generated, as well as the background image.

**Screenshots**:

screen shot 2017-09-28 at 10 18 55

screen shot 2017-09-28 at 10 19 17

screen shot 2017-09-28 at 10 18 33

**Testing instructions**:

1. Verify that you are able to generate zones and the background image, that the auto generated background image saves successfully and that it works in the LMS.
1. Verify that you can switch between auto generated and manually provided image in the Studio without issues.
1. Verify in all supported browsers.

**Author notes and concerns**:

1. I was trying to test this out in IE10 (using crossbrowsertesting) where background image sizing didn't quite work correctly. I tried using a version of DnDv2 from before we started working on mobile tweaks, and the problem was still there. In IE11 the problem wouldn't even load for me in the Studio - again this does not seem to be a new issue.

**Reviewers**:

- [ ] @bradmerlin 
- [ ] @sanfordstudent

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=136&repo=edx-solutions%2Fxblock-drag-and-drop-v2"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by bradenmacdonald** [comment]
@mtyaka Very cool :)

@sanfordstudent We have been working on some improvements to this XBlock on mobile (which unfortunately have a tight deadline), and I realized we should be getting reviews from you guys since you're now maintaining this XBlock. Sorry for not pinging you earlier or realizing this sooner (old habits...). Would you like to review these, and what's your availability for doing so?

**Comment by sanfordstudent** [comment]
@bradenmacdonald this change looks great! How tight is your deadline, and how extensive a review do you need? I will readily cop to a total lack of mobile experience but I'd be happy to take a look at this PR in more detail early next week if that works for you. And thank you for tagging me.

**Comment by bradenmacdonald** [comment]
@sanfordstudent  We basically need to deploy this within a week - but since I know that's not a reasonable period of notice for you, we could merge our PRs to a separate branch and deploy that while we wait for your review.

> how extensive a review do you need?

It's up to you - we always do a thorough review via other developers on our team, and we adhere to the same standards as edX developers do, so we're comfortable with as much or as little additional review as you'd like / have time for.

**Comment by sanfordstudent** [comment]
@bradenmacdonald no worries on the tight timeframe. I can find some time tomorrow or Monday. From my preliminary glance I don't anticipate any major change requests.

**Comment by mtyaka** [comment]
Rebased from 8b23a4a05a65482b11a82a8f13308ae515fbd557.

**Comment by bradmerlin** [comment]
:+1:

- [x] I tested this: On Safari, FF, and Chrome
  - Successfully generated the background, and used it in LMS
  - Switched between autogenerated provided backgrounds
- [x] I read through the code
- [ ] ~I checked for accessibility issues~
- [ ] ~Includes documentation~ Not much documentation, but extensive tests written

**Comment by mtyaka** [comment]
Thanks @sanfordstudent and @bradmerlin

**Pull request merged**
