### PR TITLE
add french (MCKIN-8425), german (MCKIN-8422) and japanese (MCKIN-8426) languages

### PR DESCRIPTION
**Pull request by umarmughal824**
add french (MCKIN-8425), german (MCKIN-8422) and japanese (MCKIN-8426) languages support.

### CODE REVIEW

**Comment by umarmughal824** [comment]
@xitij2000 Can you please review it?

**Comment by xitij2000** [comment]
@umarmughal824 Sure will schedule it for review.

**Comment by kaizoku** [comment]
Looks mostly good @umarmughal824 , there are a couple text fields which aren't translated in any of the languages though. I've picked Japanese here since the untranslated strings are most apparent, but the same strings aren't translated in any 3 of the languages.

"Basic Settings":
screenshot_2018-11-08 drag and drop unit ficus test course studio 5

"Maximum items per zone" and "Item Definitions"
screenshot_2018-11-08 drag and drop unit ficus test course studio 3

"Background Image", "Provide custom image", and "Generate image automatically":
screenshot_2018-11-08 drag and drop unit ficus test course studio 2

**Comment by umarmughal824** [comment]
@kaizoku Can you please check whether these unstranslated strings are being translated in other languages or not?

**Comment by xitij2000** [comment]
@umarmughal824 I think @kaizoku was pretty clear in his comment: "there are a couple text fields which **aren't translated in any of the languages** though. I've picked Japanese here since the untranslated strings are most apparent, but **the same strings aren't translated in any 3 of the languages**."

**Comment by umarmughal824** [comment]
@xitij2000 If you remember #Gaurang has told you twice about studio side strings that these are not concerned here for translation stories.

**Comment by xitij2000** [comment]
@umarmughal824 Since that discussion is not public, while this block is, it is important to make the note on the PR itself.

**Comment by umarmughal824** [comment]
@xitij2000 sounds good.

**Comment by umarmughal824** [comment]
thanks @xitij2000 , @kaizoku

**Pull request merged**
