### PR TITLE
(don't merge) run tests

### PR DESCRIPTION
**Pull request by OmarIthawi**
I just want to run Travis on a clean branch to debug #262. Nothing to be merged here.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-5569](https://openedx.atlassian.net/browse/OSPR-5569) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by mahyard** [comment]
although my pull request was failed and closed, going on to this check will prevent future issues with the tests.
Thank you @OmarIthawi @natabene

**Comment by natabene** [comment]
@OmarIthawi ok.

**Comment by OmarIthawi** [comment]
Tests seems to be working out of the box. Closing. Thanks Natalia and Mahyar.

**Comment by edx-webhook** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx-solutions/xblock-drag-and-drop-v2&entry.867055334=https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/263&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2021-01-27+19:43&entry.1917517419=2021-01-28+07:17&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
