### PR TITLE
BB-1347 Add Polish Translations

### PR DESCRIPTION
**Pull request by xirdneh**
This PR adds polish translations

**Testing instructions**:

1. Checkout branch.
2. Run `make validate_translations`

**Author notes and concerns**:

1. This PR also adds every file created by `make compile_translations` which was missing from the repo.

**Screenshots**:
Screen Shot 2019-06-13 at 10 34 53 PM
Screen Shot 2019-06-13 at 10 35 03 PM

**Reviewers**
- [ ] @xitij2000 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @xirdneh! I've created [OSPR-3643](https://openedx.atlassian.net/browse/OSPR-3643) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by xitij2000** [comment]
@natabene This is now ready for review.

**Comment by xirdneh** [comment]
@natabene Any updates on this? Thanks

**Comment by natabene** [comment]
@xirdneh sorry for delay, I was out of office for a while, let me queue this for review.

**Comment by xirdneh** [comment]
@natabene I believe so, yes. Just to make sure that the setup is an acceptable one.

**Comment by xitij2000** [comment]
@natabene Just checking in about the review :-)

**Comment by natabene** [comment]
@xitij2000 Sorry, no news yet.

**Comment by xitij2000** [comment]
@natabene Just a quick check-in about this PR. Will update if there is scope for a review soon.

**Comment by natabene** [comment]
@OmarIthawi Can you please give this a look?

**Comment by OmarIthawi** [comment]
Will do! Thanks @xirdneh!

**Comment by xitij2000** [comment]
@OmarIthawi Thanks for taking a look at this! 
I have taken up this PR from @xirdneh. I don't have enough access to transifex to change the language code, but I can change it in this PR. What would be your recommendation about this?

**Comment by natabene** [comment]
@xitij2000 I recommend with going with pl_pl. This is the 4 letter format Transifex wants us to use instead of old 2 letter format. Also, I believe, changing language code in Transifex is not possible - once created, it stays that way, so you would need to create a new Polish language resource from scratch and re-upload strings there from the original polish resource. Let me know once you are done making code changes to accommodate pl_pl.

**Comment by xitij2000** [comment]
@natabene has explained to me that the better approach would be to update this PR to use the more accurate pl_PL code. I will update this PR accordingly, in the next sprint (starting 2nd December) and merge this PR after getting the checks to pass.

**Comment by OmarIthawi** [comment]
Thanks @xitij2000! Please let me know when this is ready for another review!

**Comment by xitij2000** [comment]
@OmarIthawi Sure! Will do today.

**Comment by xitij2000** [comment]
@OmarIthawi @natabene On a second look I decided to stick with `pl` instead of `pl-pl` since that is also the [code being used by edx-platform](https://github.com/edx/edx-platform/blob/054fa85fc646076f3757b46f6025f6c641237e2f/conf/locale/config.yaml#L67) with which this needs to align.

**Comment by natabene** [comment]
@xitij2000 Great. @OmarIthawi Are you ok with this being merged now?

**Comment by natabene** [comment]
@nedbat Please merge

**Comment by xitij2000** [comment]
Thanks!

**Pull request merged**
