### PR TITLE
MCKIN-9197 fix laoding translations for spanish and chinese

### PR DESCRIPTION
**Pull request by umarmughal824**
Cherry-pick of this https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/199

### CODE REVIEW

**Comment by umarmughal824** [comment]
@xitij2000 PR is created for master branch too.

**Comment by giovannicimolin** [comment]
@umarmughal824 Do you have any news about this ticket? Do you plan to work on this next week?

**Comment by umarmughal824** [comment]
@giovannicimolin I am busy and one of my team mate will be looking into it for sure in next week.

**Comment by qazi-fahid** [comment]
@giovannicimolin We have tested this on Ginkgo and its working fine and both the PR are same, there is one line difference in both the PR but its an empty line

**Comment by xitij2000** [comment]
@qazi-fahid Both PRs are the same, but they target different branches. Additionally, xblocks need to be tested on the latest release or the master devstack on vanilla edx-platform.

**Comment by giovannicimolin** [comment]
@qazi-fahid Do you have any news on this? Can you update the PR to make it work correctly on `hawthorn.master`?

**Comment by xitij2000** [comment]
@qazi-fahid Could you please look into this? Could you specifically test on the docker devstack found at https://github.com/edx/devstack and make sure this is working properly. Ginkgo is no longer a supported release.

**Comment by qazi-fahid** [comment]
@xitij2000 i am getting the context from @umarmughal824 for this issue because he has worked on this issue and will update you when i am fully aware of the context

**Comment by umarmughal824** [comment]
@giovannicimolin will you please test it now?

**Comment by umarmughal824** [comment]
@sstack22 This has been tested and approved. Could have a look at this? According to @xitij2000 we need your review too.

**Pull request merged**
