### PR TITLE
[SOL-1998] Implement Show Answer button

### PR DESCRIPTION
**Pull request by itsjeyd**
## Description

In assessment mode, when the learner has run out of attempts, enable a "Show Answer" button. Clicking it causes all items to move to a correct placement.

## Author

@arbrandes

OpenCraft review via https://github.com/open-craft/xblock-drag-and-drop-v2/pull/10.

## Dependencies

*None*

## JIRA

- [SOL-1998](https://openedx.atlassian.net/browse/SOL-1998)

## Sandbox URLs

- [Assessment mode](http://dndv2-sol-1998.opencraft.hosting/courses/course-v1:test+tt101+run/courseware/chapter/drag_and_drop_v2/): a DnDv2 instance in assessment mode, with one maximum attempt.
- [Standard mode](http://dndv2-sol-1998.opencraft.hosting/courses/course-v1:test+tt101+run/courseware/chapter/drag_and_drop_v2_standard/): a DnDv2 instance in standard mode.

## Latest commit

- https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/101/commits/4c6fb7d74c35ef46bf4cd821d0a52320e0df7d90 *(updated 2016-09-21)*

### Assessment mode

1. Go to the [assessment mode DnDv2 instance](http://dndv2-sol-1998.opencraft.hosting/courses/course-v1:test+tt101+run/courseware/chapter/drag_and_drop_v2/) on the LMS, and log in as `staff@example.com`.
2. Click on `Staff Debug Info`, `Delete Student State`, and refresh the page.
3. Notice that there is a "Show Answer" button, because this is in assessment mode.
4. Notice that the "Show Answer" button is disabled, because this is your first attempt.  
5. Pick any item and drop it onto any zone.
6. Click submit, which will make you run out of attempts (there's only one).
7. Notice that the "Show Answer" button is now enabled.
8. Click the "Show Answer" button. Observe that:
   * All items are placed correctly
   * Decoy items are still in the bank.
   * You can't drag any of the items.
   * The "Show Answer" button is disabled.
9. Refresh the page, and see that your final attempt is displayed. **Note**: This currently only works if you did not misplace any items; a decoy item that was placed on the board counts as a misplaced item. See "Notes" below for more info.
10. Click "Show Answer" again. The same thing should happen again.

### Standard mode

1. Go to the [standard mode DnDv2 instance](http://dndv2-sol-1998.opencraft.hosting/courses/course-v1:test+tt101+run/courseware/chapter/drag_and_drop_v2_standard/) on the LMS, and log in as `staff@example.com`.
2. Notice that there is no "Show Answer" button, because this is in standard mode.

## Notes

There is an existing issue (present on master) that causes misplaced items to return to the item bank when refreshing the page after submitting the last remaining attempt for a DnDv2 problem. This PR does not include a fix for this issue. As a result, refreshing the page as described in step 9 above only produces expected results if items that were placed on the board in the final attempt are located in correct zones.

## Reviewers

- [x] OpenCraft: @itsjeyd
- [x] TNL: @cahrens and/or @staubina
- [ ] a11y: To be completed as part of [SOL-1978](https://openedx.atlassian.net/browse/SOL-1978)
- [x] Product: @sstack22

Also tagging @pdesjardins as a docs FYI.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @itsjeyd! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx-solutions%2Fxblock-drag-and-drop-v2&number=101

**Comment by itsjeyd** [comment]
@arbrandes This is looking great! :+1:

- [x] I tested this: Feature works as advertised in PR description.
- [x] I read through the code
- [x] Includes documentation

**Comment by itsjeyd** [comment]
@cahrens @staubina This is ready for you to have a look. Sandbox links are in the PR description. Thanks!

**Comment by staubina** [comment]
- [ ] Tested according to test steps
- [ ] Tested around the steps listed

I am reviewing the code changes still, but functionally it looks good.

**Comment by cahrens** [comment]
I think we should defer to product, and I'd recommend holding off on further review until product signs off. FYI, @sstack

Things that jumped out to me-- Hide Answer, icon. Not sure what else is different.

**Comment by staubina** [comment]
I have a question posted that is related to other ongoing work with Capa and that is all right now.

@cahrens Can you take a look at this as well when you have a moment?  I currently do not see anything that is concerning.

I am going to hold off pending @sstack22 comments and review.

**Comment by cahrens** [comment]
I will wait to look over the PR until product weighs in.

**Comment by sstack22** [comment]
@arbrandes - a couple comments:
- when I press show answer, a box immediately highlights the top dropzone
box on top dropzone
- We've updated Show Answer behavior so that we no longer use Hide Answer (as it does not provide much value to the learner). https://openedx.atlassian.net/browse/TNL-4936 has more details on behavior.
- The Show Answer Icon is updated as well https://openedx.atlassian.net/browse/TNL-5544

**Comment by arbrandes** [comment]
Hi @sstack22, I've addressed your comments on adcbf1c (@itsjeyd, you may want to update the PR description).  The sandbox should be updated by the time you read this.

Regarding the box highlight when pressing Show Answer: that is indicative of moving the keyboard focus to the first drop zone.  For now, I removed that altogether.  Nevertheless, it seems from TNL-4936 that when clicking Show Answer, the keyboard focus should be moved to the problem "meta" area.  The closest thing in the DnDv2 XBlock is the item bank.  If we move the focus there, however, it will be highlighted similarly: is that ok?  Or should the keyboard focus not be moved at all?

**Comment by itsjeyd** [comment]
Thanks @arbrandes, description updated.

**Comment by staubina** [comment]
When I answer a problem incorrectly and they click show answer the incorrect answer feedback popup persists, is this intentional?

screen shot 2016-09-19 at 11 11 02 am

**Comment by staubina** [comment]
One comment on the feedback noted while testing in the Assessment mode.  

Other than that Looks good to me. 👍

**Comment by cahrens** [comment]
Where is keyboard focus going on "Show Answer"?

**Comment by cahrens** [comment]
Except for my question about "Show Answer" (and AJ's question above), 👍

**Comment by arbrandes** [comment]
@staubina, thanks for the review!  Regarding the persistence of feedback when clicking Show Answer, as far as I know it should not happen.  Plus, it's a trivial fix, so I'm including it in my next push.

@cahrens, thanks as well.  The keyboard focus currently doesn't leave the Show Answer button after pressing it.  I asked [above](https://github.com/edx-solutions/xblock-drag-and-drop-v2/pull/101#issuecomment-247810224) whether I should move it to the item bank.  What do you think?

**Comment by cahrens** [comment]
@arbrandes to be consistent with how capa problems will work, the focus should move to the top of the problem so that the learner can easily navigate through and "see" the answer.

**Comment by arbrandes** [comment]
@cahrens, roger that!  In this latest push (4c6fb7d), the focus moves to the item bank, the top-most element that can be focused on.  The sandbox has been updated.

**Comment by cahrens** [comment]
👍

**Comment by itsjeyd** [comment]
Thanks @cahrens and @staubina! This looks like it's good to go.

@sstack22 Can I get you to give this a thumbs-up as well? Thanks!

**Comment by sstack22** [comment]
@itsjeyd  👍  on my end!

**Comment by itsjeyd** [comment]
Thanks @sstack22, merging now.

**Pull request merged**
