### PR TITLE
Update translations (autogenerated message)

### PR DESCRIPTION
**Pull request by OmarIthawi**
Regular translations update.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-3942](https://openedx.atlassian.net/browse/OSPR-3942) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by OmarIthawi** [comment]
@natabene This just a translations update so the XBlock is up to date with Transifex. It should be safe to merge once the Travis checks pass.

**Comment by natabene** [comment]
@OmarIthawi Sounds good. @nedbat Can you merge?

**Comment by OmarIthawi** [comment]
Thanks @nedbat!

**Pull request merged**
