### PR TITLE
version bump to 7c95f90

### PR DESCRIPTION
**Pull request by umarmughal824**
version bump to 7c95f90 which is based on updating all translations.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @umarmughal824! I've created [OSPR-2810](https://openedx.atlassian.net/browse/OSPR-2810) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by umarmughal824** [comment]
@xitij2000 will you please review it?

**Comment by umarmughal824** [comment]
@xitij2000 As the latest tag release is 2.1.1 so I have updated to 2.2.2

**Comment by xitij2000** [comment]
@umarmughal824 I'm not sure what this will accomplish? This is just merging to master so will add a version bump commit to master without including the translation because the translations are not on the master branch.

**Comment by umarmughal824** [comment]
@xitij2000 I have created the version bump PR for this xblock for edx-platform  [7c95f90](https://github.com/edx-solutions/edx-platform/pull/1268)

**Pull request closed without merging**
