### PR TITLE
MCKIN-7935-7971-7972-7641-7640: Complete tiles structure for fixed sizing

### PR DESCRIPTION
**Pull request by msaqib52**
[https://edx-wiki.atlassian.net/browse/MCKIN-7640](https://edx-wiki.atlassian.net/browse/MCKIN-7640)

### CODE REVIEW

**Comment by xitij2000** [comment]
@msaqib52  Could you address the failing tests here and update the description? It seems to be linked to a different ticket than what the PR title claims.

**Comment by xitij2000** [comment]
@jawad-khan Could you update the PR description and title to include all the changes this PR is about. Also the tests may need to be fixed.

**Comment by xitij2000** [comment]
@jawad-khan Thanks for updating the tests. This is a pretty sizable change, so it will need some additional time to test. Would you say it is ready for review now?

**Comment by jawad-khan** [comment]
@xitij2000 yes it is ready now.

**Comment by kaizoku** [comment]
Thanks @jawad-khan. Given the size of this, and since it's a few tickets combined it might take me a bit of extra time to review everything. I'll let you know once I've given it a pass though.

**Comment by kaizoku** [comment]
@jawad-khan It looks like some of the tests are still failing. Mind fixing those?

I checked out most of the functionality and it works apart from a couple small styling nitpicks.

When the detail view shows, the bottom lines fade out.
screenshot_2018-10-26 d d custom the chamber of secrets arb001 courseware your platform name here 2

When there's a scrollbar, the size isn't quite as tall as the screenshots from invision. Should these description dialogs be taller?
screenshot_2018-10-26 d d custom the chamber of secrets arb001 courseware your platform name here 1

**Comment by stvstnfrd** [comment]
@xitij2000 do you know if you still want to pursue this?

**Comment by xitij2000** [comment]
@stvstnfrd This was part of work on v4 of Drag and Drop, which introduced major UI changes. AFAIK, that effort is no longer active. A lot of that code is still here in the form of PRs, and code in the `drag-and-drop-v4` branch, so others are free to pick it up from there and run with it. 

I don't expect any further action on this PR, though. 

Perhaps @msaqib52 or @jawad-khan would know better though?

**Comment by msaqib52** [comment]
@stvstnfrd @xitij2000 no further action is required on this PR, we are good to close.

**Pull request closed without merging**
