### PR TITLE
MCKIN-9180 Translation of Reset and FEEDBACK is not working in DnD

### PR DESCRIPTION
**Pull request by umarmughal824**
MCKIN-9180 Translation of Reset and FEEDBACK is not working in DnD

### CODE REVIEW

**Comment by sstack22** [comment]
@xitij2000 - would you mind posting screenshots of before and after? That would be easiest for a review.

**Comment by umarmughal824** [comment]
@sstack22 this is [before](https://imgur.com/a/T2H43oy) and [after](https://imgur.com/a/OKuH3m4) screeshots.

See the translations for **Reset** and **Feedback** in the screenshots.

**Comment by sstack22** [comment]
Thank you! 👍 from product review.

**Comment by umarmughal824** [comment]
@sstack22 @xitij2000 Can we merge it now?

**Comment by natabene** [comment]
@xitij2000  Can you let me know why you needed edX product review for the solutions fork PR? I believe you have rights to merge it.

**Comment by xitij2000** [comment]
@natabene My understanding is that this block in particular needs an edX review before any PR is merged to master.

**Comment by natabene** [comment]
@xitij2000 Could you elaborate? Product review is not part of the normal process for PRs in the solutions fork.

**Comment by xitij2000** [comment]
@natabene I think it's because this block is also included in the standard edx-platform. However, this advice is from before my time so I'll loop in @bradenmacdonald if he could shed further light on this.

**Comment by bradenmacdonald** [comment]
@natabene This XBlock was originally developed for the Solutions fork, but it is now used on edx.org (after SOL-1403 + SOL-1803) and many other instances; it's installed by default on all Open edX installations. We have discussed with the Open Source team and agreed that this repo really should be moved from the `edx-solutions` to the `edx` GitHub organization, but so far nobody has taken the time to do that (and it's something only edX can do).

**Comment by umarmughal824** [comment]
@xitij2000 what to do with this PR? Do we need this PR anymore?

**Comment by umarmughal824** [comment]
@xitij2000 , @giovannicimolin I have finalized this PR after merging the other PR.

**Comment by umarmughal824** [comment]
@sstack22 will you please review it.

**Comment by marcotuts** [comment]
Spoke with @sstack22, ok to move this to engineering review next as this is mostly fixing broken translations, not changing behavior in any way. (@umarmughal824 - If I'm wrong about that let me know!) Thanks

**Comment by umarmughal824** [comment]
@marcotuts earlier there was no translation for *Reset & Feedback strings* but in this PR we have added these translations for *Spanish & Chinese*.

**Comment by natabene** [comment]
@ormsbee Can you give this a look please?

**Comment by umarmughal824** [comment]
@natabene I am still waiting to get it reviewed. Can you please bring me review for it?

**Comment by natabene** [comment]
@umarmughal824 Sorry for delay, is there a deadline you are trying to meet?

**Comment by umarmughal824** [comment]
@ormsbee will you please review it. I have made those changes.

**Comment by umarmughal824** [comment]
@natabene thanks for arranging the reviewer. Yes we want to merge it as soon as possible.

**Pull request merged**
