### PR TITLE
Added French (Canada) and Japanese

### PR DESCRIPTION
**Pull request by OmarIthawi**
Also updated the translations.

After adding the languages to the list I've done the following:

```
$ make pull_translations
$ make compile_translations
$ git add -A
$ git commit --message="Update translations (autogenerated message)"
```

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-3758](https://openedx.atlassian.net/browse/OSPR-3758) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@OmarIthawi Thank you for your contribution. Do you need our review? CC @bradenmacdonald

**Comment by OmarIthawi** [comment]
Thanks @natabene. Yes, that would be great!

**Comment by natabene** [comment]
@ormsbee Can you give this a quick look?

**Comment by OmarIthawi** [comment]
@natabene @ormsbee could you please check the PR? It's mostly just an update to the languages list.

**Comment by natabene** [comment]
@nedbat Could you take a look?

**Pull request merged**
