### PR TITLE
Add placeholder text to item image URL input field.  Bump version to 2.0.4.

### PR DESCRIPTION
**Pull request by smarnach**
**JIRA ticket**: [SOL-1661](https://openedx.atlassian.net/browse/SOL-1661)

**Sandbox**: [Studio](http://studio.master.dndv2.sandbox.opencraft.com/container/block-v1:TestX+TST-DNDV2-M+now+type@vertical+block@1e63181ae0c74ef4beae234aa38f7798)

**Screenshots**

Before:
image

After:
image

### CODE REVIEW

**Comment by Kelketek** [comment]
@smarnach Your build failed, but I reran (a few times) it and it went green. :+1:

**Comment by bradenmacdonald** [comment]
@mattdrayer (In case you missed the ping on JIRA): Would you mind reviewing this?

**Comment by mattdrayer** [comment]
:+1:

**Comment by smarnach** [comment]
@mattdrayer Thank you!

**Pull request merged**
