### PR TITLE
Don't delete misplaced items on final attempt

### PR DESCRIPTION
**Pull request by itsjeyd**
## Description

In assessment mode, don't delete misplaced items from the user's state when handling the final attempt.

This is a server-side change to match what Javascript already did.  In other words, upon submitting the final attempt, misplaced items were already left on the board.  However, since the corresponding state was deleted server-side, upon refreshing the page the items were returned to the bank.

## Author

@arbrandes

OpenCraft review via https://github.com/open-craft/xblock-drag-and-drop-v2/pull/13.

## Dependencies

*None*

## JIRA

*None*

## Sandbox URLs

- [LMS](http://dndv2-sol-1998.opencraft.hosting/courses/course-v1:test+tt101+run/courseware/chapter/drag_and_drop_v2/)
- [Studio](http://studio-dndv2-sol-1998.opencraft.hosting/container/block-v1:test+tt101+run+type@vertical+block@drag_and_drop_v2)

## Latest commit

- 479b8dd *(updated 2016-09-27)*

## Testing instructions

1. Go to the [pre-deployed DnDv2 instance](http://dndv2-sol-1998.opencraft.hosting/courses/course-v1:test+tt101+run/courseware/chapter/drag_and_drop_v2/) on the LMS, and log in as `staff@example.com`.
2. Click on `Staff Debug Info`, and `Delete Student State` for the `staff@example.com` user.
3. Close the debug info window, and drag a single item into its correct zone (for instance, "Goes to the Top" to the top zone).
4. Click `Submit` twice, so that you only have one attempt left.
5. Drag an item into an incorrect zone (for instance, drag "I don't belong anywhere" to the bottom zone).
6. Click `Submit`.
7. Close the incorrect answer popup.
8. Refresh the page.
9. Notice that even though you have no attempts left, the wrongly placed item is still there.

### Wrongly placed item is still there after refreshing the page.

screenshot

## Reviewers

- [x] OpenCraft: @itsjeyd
- [x] TNL: @cahrens and/or @staubina
- [ ] ~~a11y:~~ This is a bug fix that doesn't introduce new workflows (or alter existing ones). 
- [ ] Product: @sstack22

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @itsjeyd! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx-solutions%2Fxblock-drag-and-drop-v2&number=106

**Comment by itsjeyd** [comment]
@arbrandes :+1:

- [x] I tested this: Works as advertised in PR description
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ This is a bug fix that doesn't introduce new workflows (or alter existing ones).
- [ ] ~~Includes documentation~~ This is a bug fix that doesn't require documentation updates.

**Comment by itsjeyd** [comment]
@cahrens @staubina This is ready for you to have a look. Sandbox links are in the PR description. Thanks!

**Comment by cahrens** [comment]
👍 Note that you have test failures though

**Comment by staubina** [comment]
👍 Please correct failures before merging.

**Comment by arbrandes** [comment]
Trying to reproduce the failure - I'll report back shortly.

**Comment by arbrandes** [comment]
@cahrens, @staubina, I ran the full integration test suite locally, and could not reproduce any of the errors.  Looks like some Travis flakyness, as usual.

In any case, I just squashed the last fixup, and pushed again.  The code in place is exactly the same, but let's see if Travis behaves a little better this time around.

**Comment by itsjeyd** [comment]
@cahrens @staubina Thanks for reviewing!

Looks like we got a green build. Thanks @arbrandes for investigating.

@sstack2 Can I get you to have a quick look at this as well? Thanks!

**Comment by itsjeyd** [comment]
@arbrandes One more thing: To release this, we'll need to open a version bump PR against edx-platform. Could you update the version number in [`setup.py`](https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/master/setup.py#L26) and [`.travis.yml`](https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/master/.travis.yml#L12) to `2.0.11`, and add an appropriate entry to [`Changelog.md`](https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/master/Changelog.md) please? See https://github.com/edx-solutions/xblock-drag-and-drop-v2/commit/45b0e1a6dfe666bcf48acdfb4d0f7144f15cd3e6 for an example. A separate commit is fine. Thanks!

**Comment by arbrandes** [comment]
@itsjeyd, done on 83f81c7!

**Comment by bdero** [comment]
@arbrandes It looks like this is no longer a green build, can you investigate this?

@sstack22 Let me know when you've reviewed this. I was asked to merge it. Thanks!

**Comment by arbrandes** [comment]
@bdero, hey, long time no see! :)  I cannot reproduce these failures locally.  It seems, once more, these are due to Travis being flaky.  I'm just going to try issuing a rebuild, if I can - if not, I'll just push a rebase.

**Comment by bdero** [comment]
Thanks @arbrandes!

@sstack22 The tests are passing here again so this is all ready for your review. :)

**Comment by antoviaque** [comment]
@sstack22 To be able to plan for this, when would you be able to review?

**Comment by sstack22** [comment]
@antoviaque  - thanks for the ping :) I'll review now.

**Comment by sstack22** [comment]
👍 !

**Comment by antoviaque** [comment]
@sstack22 Great, thank you : )

**Pull request merged**
