### PR TITLE
Add Portuguese (Portugal) translations

### PR DESCRIPTION
**Pull request by MoisesGSalas**
### Description
Adds the translations for the Portuguese of Portugal language

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @MoisesGSalas! I've created [OSPR-5933](https://openedx.atlassian.net/browse/OSPR-5933) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by MoisesGSalas** [comment]
Hi @natabene, do you know of someone that can check this or if I missed any steps.

**Comment by natabene** [comment]
@MoisesGSalas Thank you for your contribution. Please note that we cannot review before we sort out your contributor agreement situation.  Also, we add translations via [Transifex](https://www.transifex.com/open-edx/edx-platform/).

**Comment by natabene** [comment]
@giovannicimolin Do you want to review this one as well?

**Comment by giovannicimolin** [comment]
@natabene Is it ok for me to review this? I'm not marked as CC for this repo but I have permission to merge.

**Comment by natabene** [comment]
@giovannicimolin Please review, and let me know once it is ready to merge, but don't merge yet. Thanks

**Comment by giovannicimolin** [comment]
@natabene I have this lined up for review this sprint (which started today). I'll let you know once this is complete.

**Review by giovannicimolin — CHANGES_REQUESTED** [review]
@MoisesGSalas I've tested this and it's working perfectly on a master devstack.

Before I approve this, can you add a version bump to the PR? Change [this line](https://github.com/edx-solutions/xblock-drag-and-drop-v2/blob/master/setup.py#L26) to `2.3.6`.

**Comment by MoisesGSalas** [comment]
@giovannicimolin done. Tell me if there's anything else you need. 

Thanks again for your time.

**Review by giovannicimolin — APPROVED** [review]
:+1:

- [x] I tested this: 
1. Installed this on a `master` devstack.
2. Checked that the `pt_PT` translations were being displayed correctly. 
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ NA: just pulling a new translation.
- [ ] ~~Includes documentation~~ NA

@MoisesGSalas Nice work! Thanks for the contribution.

@natabene This approved and ready to merge now.

**Comment by natabene** [comment]
@giovannicimolin Thank you for reviewing and letting me know. @MoisesGSalas Before we merge, we need to have certain documentation in place. I will reach out to your employer to get this sorted out. Once it is ready, I will let @giovannicimolin know it can be merged.

**Comment by natabene** [comment]
@giovannicimolin I have sorted out the paperwork and this is good to go now, please merge at your earliest convenience.

**Comment by giovannicimolin** [comment]
@natabene PR merged and release created.

**Pull request merged**
