### PR TITLE
Version bump: v2.0.9

### PR DESCRIPTION
**Pull request by e-kolpakov**
**Description:** This PR bumps drag-and-drop-v2 version to 2.0.8

**JIRA:** [SOL-1803](https://openedx.atlassian.net/browse/SOL-1803)

**Motivation:** Updating to v2.0.9 to include in the upcoming edx-platform release (Sep 2nd)

**Merge deadline:** Sep 2nd.

**Reviewers:**
- [x] @smarnach 
- [x] @cahrens
- [ ] @sstack22

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @e-kolpakov! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx-solutions%2Fxblock-drag-and-drop-v2&number=100

**Comment by e-kolpakov** [comment]
@smarnach I hope to get #93 merged today, so this is not actually ready yet - just using some free time (while CI build is running) to prepare for later.

**Comment by e-kolpakov** [comment]
@cahrens @sstack22 ping - PR for v2.0.9 - it would be great to have it reviewed today so I can merge it first thing tomorrow morning.

I'm also trying to land #93 in time for v2.0.9, but if it lands tomorrow this PR will only need one line of Changelog added.

**Comment by cahrens** [comment]
👍

**Comment by e-kolpakov** [comment]
@cahrens Thank you for very quick response!

**Comment by sstack22** [comment]
👍 !

**Comment by e-kolpakov** [comment]
@smarnach This PR is tiny, quite important and waits for your review - please take a look ASAP (shouldn't take more than a minute of your time)

**Comment by smarnach** [comment]
:+1:

**Comment by e-kolpakov** [comment]
@smarnach Thank you!

**Pull request merged**
