### PR TITLE
MCKIN-11247 Added dragging class on zones while dragging an item

### PR DESCRIPTION
**Pull request by nasirhjafri**
Added dragging class on zones while dragging an item

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @nasirhjafri! I've created [OSPR-3719](https://openedx.atlassian.net/browse/OSPR-3719) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by msaqib52** [comment]
@nasirhjafri I think this PR should be against `v3-temporary-branch` branch since mcka is using this branch for v2-new.

**Comment by nasirhjafri** [comment]
@msaqib52 I don't see any branch named `v3-temporary-branch`

**Comment by msaqib52** [comment]
@nasirhjafri my bad that is in another [fork](https://github.com/open-craft/xblock-drag-and-drop-v2) which MCKA is using.

**Pull request merged**
