### PR TITLE
RTL fixes

### PR DESCRIPTION
**Pull request by pomegranited**
## Description

Introduce proper right-to-left support for the following:

* Alignment of overall feedback message icons and text
* Alignment and borders of sidebar buttons
* Margin of the "You have used X attempts" message

## Dependencies

*None*

## JIRA

- [SOL-2031](https://openedx.atlassian.net/browse/SOL-2031)

## Sandbox URLs

- [LMS](http://dndv2-pr96.opencraft.hosting/courses/course-v1:test+tt101+run/courseware/chapter/drag_and_drop_v2/)
- [Studio](http://studio-dndv2-pr96.opencraft.hosting/container/block-v1:test+tt101+run+type@vertical+block@drag_and_drop_v2)

## Latest commit

- fe49f58 *(updated 2016-09-14)*

## Testing instructions

1. Go to the pre-deployed assessment-mode block on the [LMS](http://dndv2-pr96.opencraft.hosting/courses/course-v1:test+tt101+run/courseware/chapter/drag_and_drop_v2/), and log in as `staff@example.com`.
2. Click on `Staff Debug Info`, and `Delete Student State` for the `staff@example.com` user.  Close the modal.
3. Pick a regular item and place it correctly in its zone.  Click submit, and notice that there are now 3 overall feedback messages, all of them correctly aligned.
4. [Update the language](http://dndv2-pr96.opencraft.hosting/update_lang/) to `ar`.
5. Go back to the block and refresh the page.
6. Notice that in Arabic, the feedback message icons are properly aligned on the right.
7. Notice that the sidebar buttons (reset and keyboard help) are properly aligned on the left.
8. Notice that the "You have used X attempts" message is properly spaced away from the submit button.

## Screenshots

oc1859-1

## Reviewers

- [x] OpenCraft: @pomegranited
- [ ] TNL: @cahrens or @staubina
- [ ] a11y: @cptvitamin or @clrux - did you want to have a look at this too?
- [ ] Product: @marcotuts (CC @sstack22)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @pomegranited! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=102&repo=edx-solutions%2Fxblock-drag-and-drop-v2

**Comment by cahrens** [comment]
These changes are also included in #103, correct?

**Comment by pomegranited** [comment]
@cahrens My apologies!  I accidentally merged this branch into our fork, and when @arbrandes rebased his branch for #103, it included those changes in that PR as well.

How would you like me to proceed?  I can combine the review for both PRs into #103 and close this PR..  or try to untangle the merge.. or leave things as-is?

**Comment by cahrens** [comment]
@pomegranited no problem-- I'd say close this PR and just have the review be in #103.

**Comment by pomegranited** [comment]
Closing this PR as the changes are included in #103.

**Comment by arbrandes** [comment]
@pomegranited, sorry for my part in the confusion with the rebase.  I mistook the merge to opencraft master as having come from edx-solutions master.

**Pull request closed without merging**
